### ISSUE TITLE
`zero` OpenType feature: One zero is slightly higher than the other.

### ISSUE THREAD

**Issue by ctrlcctrlv** [SorkinType/Calistoga#2]
I think the zeros should both sit on the baseline. Perhaps they would never be used together, but this makes it so when you use it with other numbers it looks strange.

![2019-08-30-144531_1356x967_scrot](https://user-images.githubusercontent.com/838783/63998931-e3acc780-cb34-11e9-9aa7-457a0ca988a4.png)

![2019-08-30-144409_1356x967_scrot](https://user-images.githubusercontent.com/838783/63998804-929cd380-cb34-11e9-8146-3e9d913f9c8c.png)

**Comment by EbenSorkin** [comment]
Good catch!

**Comment by EbenSorkin** [comment]
I have corrected this in the source file. I'll check with Marc and Viviana about rolling it into the fonts and making it live next.
